"""
Simple Model Compare Sampler - Works like standard KSampler but handles multiple model comparisons.
Supports FLUX and QWEN models.
"""

import torch
import folder_paths
import comfy.sd
import comfy.utils
from typing import List, Dict, Tuple, Any


class SamplerCompareSimple:
    """
    Simple sampler for model comparison.
    Takes a config with multiple LoRA combinations and samples each one.
    Works exactly like ComfyUI's standard KSampler for each iteration.
    Supports FLUX and QWEN diffusion models.
    """
    
    RETURN_TYPES = ("IMAGE", "STRING")
    RETURN_NAMES = ("images", "labels")
    FUNCTION = "sample_all_combinations"
    CATEGORY = "sampling"
    OUTPUT_NODE = True

    @classmethod
    def INPUT_TYPES(cls):
        import comfy.samplers
        
        # Get available samplers and schedulers
        samplers = comfy.samplers.KSampler.SAMPLERS
        schedulers = comfy.samplers.KSampler.SCHEDULERS
        
        # Convert to lists if they're dicts, otherwise use as-is
        sampler_list = list(samplers.keys()) if isinstance(samplers, dict) else list(samplers)
        scheduler_list = list(schedulers.keys()) if isinstance(schedulers, dict) else list(schedulers)
        
        return {
            "required": {
                "config": ("MODEL_COMPARE_CONFIG",),
                "model": ("MODEL",),
                "positive": ("CONDITIONING",),
                "negative": ("CONDITIONING",),
                "latent": ("LATENT",),
                "vae": ("VAE",),
                "steps": ("INT", {"default": 20, "min": 1, "max": 10000}),
                "cfg": ("FLOAT", {"default": 7.0, "min": 0.0, "max": 100.0, "step": 0.1}),
                "sampler_name": (sampler_list,),
                "scheduler": (scheduler_list,),
                "seed": ("INT", {"default": 0, "min": 0, "max": 0xffffffffffffffff}),
                "denoise": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 1.0, "step": 0.01}),
            }
        }

    def sample_all_combinations(
        self,
        config: Dict[str, Any],
        model,
        positive,
        negative,
        latent,
        vae,
        steps: int,
        cfg: float,
        sampler_name: str,
        scheduler: str,
        seed: int,
        denoise: float,
    ) -> Tuple[torch.Tensor, str]:
        """
        Sample each combination in config.
        Each combination specifies which LoRAs to load and at what strength.
        CLIP variations are tracked for reference/labeling purposes.
        Uses the same sampling pipeline as ComfyUI's standard KSampler.
        """
        from nodes import common_ksampler
        
        combinations = config.get("combinations", [])
        if not combinations:
            raise ValueError("No combinations in config")
        
        all_images = []
        all_labels = []
        
        print(f"[SamplerCompareSimple] Sampling {len(combinations)} combinations...")
        
        for idx, combo in enumerate(combinations):
            print(f"\n[SamplerCompareSimple] === Combination {idx} ===")
            
            # Get LoRA info from combo
            lora_names = combo.get("lora_names", [])
            lora_strengths = combo.get("lora_strengths", ())
            lora_display_names = combo.get("lora_display_names", lora_names)
            
            # Get CLIP variation info (for reference/labeling only)
            clip_var = combo.get("clip_variation")
            
            print(f"[SamplerCompareSimple] LoRAs: {lora_names}")
            print(f"[SamplerCompareSimple] Strengths: {lora_strengths}")
            if clip_var:
                print(f"[SamplerCompareSimple] CLIP variation type: {clip_var.get('type')}")
            
            # Clone base model for this iteration
            working_model = model.clone() if hasattr(model, 'clone') else model
            
            # Apply LoRAs to the cloned model
            if lora_names and lora_strengths:
                working_model = self._apply_loras(working_model, lora_names, lora_strengths)
            
            # Sample with this model using standard KSampler pipeline
            # Note: conditioning was pre-generated by upstream nodes with a specific CLIP
            print(f"[SamplerCompareSimple] Sampling with seed {seed}, denoise {denoise}")
            sampled = common_ksampler(
                model=working_model,
                seed=seed,
                steps=steps,
                cfg=cfg,
                sampler_name=sampler_name,
                scheduler=scheduler,
                positive=positive,
                negative=negative,
                latent=latent,
                denoise=denoise,
            )
            
            sampled_latent = sampled[0]
            
            # Decode latent to image
            print(f"[SamplerCompareSimple] Decoding with VAE")
            image = self._decode_latent(sampled_latent, vae)
            all_images.append(image)
            
            # Create label for this combination
            # Use the last LoRA's display name and strength as the varied parameter
            if lora_display_names:
                varied_lora_idx = len(lora_display_names) - 1
                label = f"{lora_display_names[varied_lora_idx]}({lora_strengths[varied_lora_idx]:.2f})"
            else:
                label = f"Combination {idx}"
            
            all_labels.append(label)
            print(f"[SamplerCompareSimple] Label: {label}")
        
        # Concatenate all images
        print(f"\n[SamplerCompareSimple] Generated {len(all_images)} images")
        images_tensor = torch.cat(all_images, dim=0)
        labels_str = "\n".join(all_labels)
        
        return (images_tensor, labels_str)
    
    @staticmethod
    def _apply_loras(model, lora_names: List[str], strengths: Tuple[float, ...]):
        """Apply LoRAs to the model, skipping zero-strength LoRAs."""
        import comfy.utils
        
        working_model = model
        
        for lora_name, strength in zip(lora_names, strengths):
            if strength == 0.0:
                print(f"[SamplerCompareSimple] Skipping LoRA '{lora_name}' (strength 0.0)")
                continue
            
            lora_path = folder_paths.get_full_path_or_raise("loras", lora_name)
            lora_data = comfy.utils.load_torch_file(lora_path, safe_load=True)
            
            print(f"[SamplerCompareSimple] Applying LoRA '{lora_name}' at strength {strength}")
            
            # Apply LoRA using ComfyUI's standard function
            # clip_model is None since we don't modify text encoding in comparison
            working_model, _ = comfy.sd.load_lora_for_models(
                working_model, None, lora_data, strength, strength
            )
        
        return working_model
    
    @staticmethod
    def _decode_latent(latent_dict, vae):
        """Decode latent samples to image using VAE."""
        if isinstance(latent_dict, dict) and "samples" in latent_dict:
            samples = latent_dict["samples"]
        else:
            samples = latent_dict
        
        # Decode using VAE
        image = vae.decode(samples)
        
        # Handle 5D tensors (frame dimension) - common with QWEN and other video models
        if image.dim() == 5:
            # Shape: [batch, frames, height, width, channels]
            # Take first frame if multiple
            image = image[:, 0:1, :, :, :]
        
        # Ensure shape is [batch, height, width, channels]
        if image.dim() == 5:
            image = image.squeeze(1)
        
        return image


# Node class mappings
NODE_CLASS_MAPPINGS = {
    "SamplerCompareSimple": SamplerCompareSimple,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "SamplerCompareSimple": "Sampler Compare Simple",
}
